stages:
  - build
  - tag
  - push

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never

build:
  stage: build
  before_script:
    - export VERSION=$(jq -r '.version?' ./package.json)
    - mkdir -p .ssh && cp $GIT_CONFIG .ssh/config && cp  ~/.ssh/id_rsa .ssh/id_rsa
  script: /usr/bin/docker build -t "$NEXUS/lforms/flowsheet-lhc:$VERSION" --build-arg NODE_ENV=production . 
  only:
    - cicd 
    - tags
  tags: [cmd]


tag:
  stage: tag
  before_script:
    - export VERSION=$(shell jq -r '.version?' ./package.json)
  script: /usr/bin/docker tag $NEXUS/lforms/flowsheet-lhc:$VERSION $NEXUS/lforms/flowsheet-lhc:latest 
  only:
    - cicd
    - tags
  tags: [cmd]


push:
  stage: push
  before_script:
    - /usr/bin/docker login $NEXUS -u $NEXUS_USER -p $NEXUS_PASSWORD 
  script: /usr/bin/docker build push $NEXUS/lforms/flowsheet-lhc:$VERSION 
  only:
    - cicd
    - tags
  tags: [cmd]
